"""Tiered incident report publishing via Ghost CMS.

Publishes TWO reports per incident using Ghost's membership visibility tiers:
  - Executive report (``visibility="public"``): high-level status, impact,
    ETA, action taken — accessible to anyone.
  - Engineering report (``visibility="paid"``): full root cause, metrics,
    data sources, remediation steps, Macroscope analysis, call transcript,
    and Overmind trace — restricted to paid members (i.e. the engineering
    team with paid Ghost membership).

This is the CREATIVE use of Ghost — not just a blog, but a structured incident
communication platform with audience-based visibility tiers.  Ghost supports
four visibility levels: ``public``, ``members``, ``paid``, ``tiers``.

Ref: https://docs.ghost.org/admin-api/posts/creating-a-post
"""

import logging
import uuid
from datetime import datetime, timezone
from typing import Any, Optional

from sentinelcall.ghost_publisher import GhostPublisher

logger = logging.getLogger(__name__)

# -- HTML Templates --

_SHARED_STYLE = """
<style>
    .sc-report { font-family: 'Inter', -apple-system, sans-serif; color: #e0e0e0; background: #1a1a2e; padding: 32px; border-radius: 12px; }
    .sc-report h2 { color: #00d4ff; margin-top: 24px; }
    .sc-report h3 { color: #b0b0cc; }
    .sc-report .sc-badge { display: inline-block; padding: 4px 12px; border-radius: 4px; font-weight: 700; font-size: 14px; }
    .sc-badge-p0 { background: #ff1744; color: #fff; }
    .sc-badge-p1 { background: #ff9100; color: #1a1a2e; }
    .sc-badge-p2 { background: #ffd600; color: #1a1a2e; }
    .sc-badge-p3 { background: #69f0ae; color: #1a1a2e; }
    .sc-report .sc-metric { background: #16213e; padding: 12px 16px; border-left: 3px solid #00d4ff; margin: 8px 0; border-radius: 4px; }
    .sc-report .sc-footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #333; font-size: 12px; color: #666; }
    .sc-report code { background: #16213e; padding: 2px 6px; border-radius: 3px; color: #69f0ae; }
    .sc-report pre { background: #0d1117; padding: 16px; border-radius: 8px; overflow-x: auto; color: #c9d1d9; }
    .sc-report table { width: 100%; border-collapse: collapse; margin: 12px 0; }
    .sc-report th, .sc-report td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #333; }
    .sc-report th { color: #00d4ff; font-weight: 600; }
</style>
"""


def _severity_badge(severity: str) -> str:
    """Return an HTML badge for the severity level."""
    sev = severity.upper().replace("SEV-", "P").replace("-", "")
    css_class = {
        "P0": "sc-badge-p0",
        "P1": "sc-badge-p1",
        "P2": "sc-badge-p2",
        "P3": "sc-badge-p3",
    }.get(sev, "sc-badge-p2")
    return f'<span class="sc-badge {css_class}">{severity}</span>'


def _timestamp_footer() -> str:
    """Return a timestamped footer."""
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    return (
        f'<div class="sc-footer">'
        f"Auto-generated by Pager0 at {ts}"
        f"</div>"
    )


class IncidentReportPublisher:
    """Publish tiered incident reports to Ghost CMS."""

    def __init__(self, ghost_publisher: GhostPublisher | None = None):
        self.ghost = ghost_publisher or GhostPublisher()
        self._report_urls: list[dict[str, Any]] = []

    def publish_incident_report(
        self, incident: dict[str, Any], diagnosis: dict[str, Any]
    ) -> dict[str, Any]:
        """Publish executive and engineering incident reports.

        Args:
            incident: Dict with ``incident_id``, ``service``, ``severity``,
                ``description``, ``started_at``, ``status``.
            diagnosis: Dict with ``root_cause``, ``metrics_snapshot``,
                ``airbyte_sources``, ``remediation_steps``,
                ``macroscope_analysis``, ``bland_transcript``,
                ``overmind_trace``, ``eta_minutes``, ``action_taken``.

        Returns:
            Dict with ``executive_report`` and ``engineering_report`` results.
        """
        incident_id = incident.get("incident_id", f"INC-{uuid.uuid4().hex[:8]}")
        severity = incident.get("severity", "SEV-2")

        exec_result = self._publish_executive_report(incident_id, severity, incident, diagnosis)
        eng_result = self._publish_engineering_report(incident_id, severity, incident, diagnosis)

        self._report_urls.append({
            "incident_id": incident_id,
            "executive_url": exec_result.get("url"),
            "engineering_url": eng_result.get("url"),
        })

        logger.info(
            "Published tiered reports for %s: exec=%s eng=%s",
            incident_id,
            exec_result.get("url"),
            eng_result.get("url"),
        )

        return {
            "executive_report": exec_result,
            "engineering_report": eng_result,
        }

    def get_report_urls(self) -> list[dict[str, Any]]:
        """Return URLs of all published incident reports."""
        return list(self._report_urls)

    # -- Private report builders --

    def _publish_executive_report(
        self,
        incident_id: str,
        severity: str,
        incident: dict[str, Any],
        diagnosis: dict[str, Any],
    ) -> dict[str, Any]:
        """Build and publish the public executive summary."""
        service = incident.get("service", "unknown-service")
        description = incident.get("description", "Production anomaly detected.")
        status = incident.get("status", "investigating")
        eta = diagnosis.get("eta_minutes", 15)
        action = diagnosis.get("action_taken", "Automated remediation initiated.")
        impact = diagnosis.get("impact", "Elevated error rates affecting end-users.")

        html = f"""
{_SHARED_STYLE}
<div class="sc-report">
    <h2>Incident Report: {incident_id}</h2>
    <p>{_severity_badge(severity)} &nbsp; Service: <strong>{service}</strong></p>

    <div class="sc-metric"><strong>Status:</strong> {status.title()}</div>
    <div class="sc-metric"><strong>Impact:</strong> {impact}</div>
    <div class="sc-metric"><strong>ETA to Resolution:</strong> {eta} minutes</div>

    <h3>Action Taken</h3>
    <p>{action}</p>

    <h3>Summary</h3>
    <p>{description}</p>

    {_timestamp_footer()}
</div>
"""
        title = f"[{severity}] {service} — Incident {incident_id}"
        tags = ["incident", severity.lower(), "executive-summary"]

        return self.ghost.publish_post(
            title=title,
            html=html,
            tags=tags,
            visibility="public",
            featured=(severity in ("SEV-0", "SEV-1", "P0", "P1")),
        )

    def _publish_engineering_report(
        self,
        incident_id: str,
        severity: str,
        incident: dict[str, Any],
        diagnosis: dict[str, Any],
    ) -> dict[str, Any]:
        """Build and publish the members-only engineering deep-dive."""
        service = incident.get("service", "unknown-service")
        description = incident.get("description", "Production anomaly detected.")
        root_cause = diagnosis.get("root_cause", "Under investigation.")
        metrics = diagnosis.get("metrics_snapshot", {})
        airbyte_sources = diagnosis.get("airbyte_sources", [])
        remediation_steps = diagnosis.get("remediation_steps", [])
        macroscope = diagnosis.get("macroscope_analysis", {})
        transcript = diagnosis.get("bland_transcript", "")
        overmind_trace = diagnosis.get("overmind_trace", "")

        # Metrics table
        metrics_rows = ""
        for k, v in (metrics if isinstance(metrics, dict) else {}).items():
            metrics_rows += f"<tr><td><code>{k}</code></td><td>{v}</td></tr>\n"
        metrics_html = f"""
    <table>
        <tr><th>Metric</th><th>Value</th></tr>
        {metrics_rows}
    </table>
""" if metrics_rows else "<p>No metrics snapshot available.</p>"

        # Airbyte sources
        airbyte_html = ""
        if airbyte_sources:
            items = "".join(f"<li>{src}</li>" for src in airbyte_sources)
            airbyte_html = f"<ul>{items}</ul>"
        else:
            airbyte_html = "<p>No dynamic Airbyte connectors created for this incident.</p>"

        # Remediation steps
        remediation_html = ""
        if remediation_steps:
            items = "".join(f"<li>{step}</li>" for step in remediation_steps)
            remediation_html = f"<ol>{items}</ol>"
        else:
            remediation_html = "<p>No remediation steps recorded.</p>"

        # Macroscope analysis
        if macroscope:
            pr_num = macroscope.get("pr_number", "N/A")
            pr_title = macroscope.get("pr_title", "Unknown")
            confidence = macroscope.get("confidence", "N/A")
            explanation = macroscope.get("explanation", "")
            macroscope_html = f"""
    <div class="sc-metric">
        <strong>Causal PR:</strong> #{pr_num} — {pr_title}<br>
        <strong>Confidence:</strong> {confidence}<br>
        <strong>Analysis:</strong> {explanation}
    </div>
"""
        else:
            macroscope_html = "<p>No Macroscope analysis available.</p>"

        # Transcript
        transcript_html = (
            f"<pre>{transcript}</pre>" if transcript
            else "<p>No Bland AI call transcript recorded.</p>"
        )

        # Overmind trace
        overmind_html = (
            f"<pre>{overmind_trace}</pre>" if overmind_trace
            else "<p>No Overmind decision trace available.</p>"
        )

        html = f"""
{_SHARED_STYLE}
<div class="sc-report">
    <h2>Engineering Report: {incident_id}</h2>
    <p>{_severity_badge(severity)} &nbsp; Service: <strong>{service}</strong></p>
    <p>{description}</p>

    <h2>Root Cause</h2>
    <p>{root_cause}</p>

    <h2>Metrics Snapshot</h2>
    {metrics_html}

    <h2>Airbyte Data Sources</h2>
    {airbyte_html}

    <h2>Remediation Steps</h2>
    {remediation_html}

    <h2>Macroscope Analysis (PR-Linked Root Cause)</h2>
    {macroscope_html}

    <h2>Bland AI Call Transcript</h2>
    {transcript_html}

    <h2>Overmind Decision Trace</h2>
    {overmind_html}

    {_timestamp_footer()}
</div>
"""
        title = f"[ENG] [{severity}] {service} — Incident {incident_id}"
        tags = ["incident", severity.lower(), "engineering-report"]

        return self.ghost.publish_post(
            title=title,
            html=html,
            tags=tags,
            visibility="paid",
            featured=False,
        )
